### ISSUE TITLE
Untracked HTML files in the antora directory

### ISSUE THREAD

**Issue by themr0c** [ahus1/keycloak-antora#6]
`npm run author` creates HTML files, that Git should probably ignore:

```
Untracked files:
        antora/guides-keycloak-operator.html
        antora/guides-keycloak-server.html
        antora/keycloak-documentation.html
        antora/keycloak-server-administration.html
```

**Comment by ahus1** [comment]
@themr0c - this might be a left-over when using the JavaScript based asciidoctor-pdf version. I don't see this happen when using the Ruby based asciidoctor-pdf version. 

Could you please have a look? Thanks!

**Comment by themr0c** [comment]
Will do

**Comment by ahus1** [comment]
I'm assuming this is resolved; please comment if it isn't.
